#k8s/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
      name: frontend
spec:
      replicas: 1
      selector:
            matchLabels:
                  app: frontend
      template:
            metadata:
                  labels:
                        app: frontend
            spec:
                  containers:
                        - name: frontend
                          image: wheezybatom/my-frontend-image:latest
                          env:
                                - name: VITE_KEYCLOAK_URL
                                  value: "http://localhost:8080/realms/myrealm"
                                - name: VITE_KEYCLOAK_CLIENT_ID
                                  value: "myclient"
                          ports:
                                - containerPort: 80
                          resources:
                                limits:
                                      memory: "128Mi"
                                      cpu: "500m"
                                requests:
                                      memory: "64Mi"
                                      cpu: "250m"
